model:
  name: 
    UNetModule
  kwargs:
    spatial_dims:
      3
    in_channels:
      1
    out_channels:
      1
    channels:
      [2, 4]
    strides:
      [2]
    kernel_size:
      3
data:
  name:
    HeartDataModule
  kwargs:
    root:
      data
    batch_size:
      2
    val_split:
      0.1
    num_workers:
      0
    transforms_kwargs:
      train:
        - name:
            LoadImaged
          kwargs:
            keys: ['image', 'label']
        - name:
            EnsureChannelFirstd
          kwargs:
            keys: ['image', 'label']
        - name:
            NormalizeIntensityd
          kwargs:
            keys: ['image', 'label']
        - name:
            RandFlipd
          kwargs:
            keys: ['image', 'label']
        - name:
            RandAffined
          kwargs:
            keys: ['image', 'label']
            rotate_range: [0, 180]
            scale_range: [0.9, 1.1]
        - name:
            DivisiblePadd
          kwargs:
            keys: ['image', 'label']
            k: 2
        - name:
            ToTensord
          kwargs:
            keys: ['image', 'label']
      val:
        - name:
            LoadImaged
          kwargs:
            keys: ['image', 'label']
        - name:
            EnsureChannelFirstd
          kwargs:
            keys: ['image', 'label']
        - name:
            NormalizeIntensityd
          kwargs:
            keys: ['image', 'label']
        - name:
            DivisiblePadd
          kwargs:
            keys: ['image', 'label']
            k: 2
        - name:
            ToTensord
          kwargs:
            keys: ['image', 'label']
      test:
        - name:
            LoadImage
          kwargs:
        - name:
            EnsureChannelFirst
          kwargs:
        - name: 
            NormalizeIntensity
          kwargs:
        - name:
            DivisiblePad
          kwargs:
            k: 2
        - name:
            ToTensor
          kwargs:
