[trainer]
max_epochs=100
accelerator="cuda"
log_every_n_steps=1

[loggers]
names = ["WandbLogger", "TensorBoardLogger"]
WandbLogger.name = "UNet"
WandbLogger.project = "medical_segmentation_decathlon"
WandbLogger.group = "train"
TensorBoardLogger.save_dir = "logs"
WandbLogger.log_model = true

[model]
name = "UNetModule"
kwargs.spatial_dims = 3
kwargs.in_channels = 1
kwargs.out_channels = 2
kwargs.channels = [16, 32, 64, 128, 256]
kwargs.strides = [2, 2, 2, 2]
kwargs.kernel_size = 3

[model.optimizer_config]
name = "Adam"
kwargs.lr = 3e-4

[data]
name = "HeartDataModule"
kwargs.root = "data"
kwargs.batch_size = 1
kwargs.val_split = 0.1
kwargs.num_workers = 0

[data.kwargs.transforms_kwargs.train]
names = ["LoadImaged", "EnsureChannelFirstd", "NormalizeIntensityd", "RandFlipd", "RandAffined", "DivisiblePadd", "ToTensord"]
LoadImaged.keys = ["image", "label"]
EnsureChannelFirstd.keys = ["image", "label"]
NormalizeIntensityd.keys = ["image"]
RandFlipd.keys = ["image", "label"]
RandAffined.keys = ["image", "label"]
DivisiblePadd.keys = ["image", "label"]
DivisiblePadd.k = 16
ToTensord.keys = ["image", "label"]

[data.kwargs.transforms_kwargs.val]
names = ["LoadImaged", "EnsureChannelFirstd", "NormalizeIntensityd", "DivisiblePadd", "ToTensord"]
LoadImaged.keys = ["image", "label"]
EnsureChannelFirstd.keys = ["image", "label"]
NormalizeIntensityd.keys = ["image"]
DivisiblePadd.keys = ["image", "label"]
DivisiblePadd.k = 16
ToTensord.keys = ["image", "label"]

[data.kwargs.transforms_kwargs.test]
names = ["LoadImage", "EnsureChannelFirst", "NormalizeIntensity", "DivisiblePad", "ToTensor"]
DivisiblePad.k = 16
